version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.0.0
    - 13.0.1
    - 13.0.10
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.3
    - 13.1.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.5
